name: clean_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod/install
  flutter_riverpod: ^2.6.1
  # https://pub.dev/packages/go_router/install
  go_router: ^14.8.0
  # https://pub.dev/packages/retrofit/install
  retrofit: ^4.4.2
  # https://pub.dev/packages/dio
  dio: ^5.8.0+1
  # https://pub.dev/packages/dio_http_formatter/install
  dio_http_formatter: ^3.3.0
  # https://pub.dev/packages/freezed_annotation/install
  freezed_annotation: ^2.4.4
  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.9.0
  # https://pub.dev/packages/intl/install
  intl: ^0.19.0
  # https://pub.dev/packages/flutter_secure_storage/install
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # https://pub.dev/packages/build_runner/install
  build_runner: ^2.4.15
  # https://pub.dev/packages/retrofit_generator/install
  retrofit_generator: ^9.1.9
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.4
  # https://pub.dev/packages/freezed
  freezed: ^2.5.8
  # https://pub.dev/packages/riverpod_generator/install
  riverpod_generator: ^2.6.4
  # https://pub.dev/packages/flutter_gen_runner/install
  flutter_gen_runner: ^5.9.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazirB.ttf
        - asset: assets/fonts/vazirL.ttf
        - asset: assets/fonts/vazirM.ttf